// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_project_region': 'us-west-2',
    'aws_cognito_identity_pool_id': 'us-west-2:4f678d62-1ddf-4270-b223-256998d12785',
    'aws_cognito_region': 'us-west-2',
    'aws_user_pools_id': 'us-west-2_rLAPZ8nyL',
    'aws_user_pools_web_client_id': '3bvvl27n1a8k3okonkukuv2d7a'
};


export default awsmobile;
